# Generated by Django 4.0.6 on 2022-08-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('city', models.CharField(max_length=30)),
                ('link', models.CharField(default='https://www.region-zoloto.ru/', max_length=100)),
            ],
            options={
                'verbose_name': 'Филиал',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GemToBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('form', models.CharField(choices=[('Круглый', 'R57'), ('Кушон', 'Cushion'), ('Маркиз', 'Marquise'), ('Овал', 'Oval'), ('Груша', 'Pear')], max_length=30)),
                ('image', models.CharField(max_length=300)),
                ('size', models.CharField(max_length=30)),
                ('def_gia', models.CharField(choices=[('VS1', 'Vs1'), ('VVS1', 'Vvs1'), ('SI1', 'Si1'), ('SI2', 'Si2')], max_length=10)),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetalToBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=800)),
                ('sort', models.CharField(choices=[('Гранула', 'Granule'), ('Слиток', 'Bullion'), ('Мерный слиток', 'Bullion Bars'), ('Стандартный слиток', 'Bullion Standard'), ('Порошок', 'Powder'), ('Пластина', 'Plate')], max_length=30)),
                ('price_with_nds', models.IntegerField()),
                ('price_without_nds', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetalToSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('metal', models.CharField(choices=[('Золото', 'Gold'), ('Серебро', 'Silver'), ('Платина', 'Platinum'), ('Палладий', 'Palladium')], max_length=30)),
                ('cash_comment', models.CharField(max_length=50, null=True)),
                ('card_comment', models.CharField(max_length=50, null=True)),
                ('transfer_comment', models.CharField(max_length=50, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.cityinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('word', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('direct_link', models.CharField(max_length=150)),
                ('preview_image_link', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('is_send', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('text', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Отзыв/Идея',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(default=None, max_length=128, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('news', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ПользовательТг',
            },
        ),
        migrations.CreateModel(
            name='UserNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('word', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.tguser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TgAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.tguser')),
            ],
            options={
                'verbose_name': 'АдминТг',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('Новый', 'New'), ('Созданный', 'Created'), ('Подтвержден менеджером', 'Confirmed')], max_length=30)),
                ('phone_number', models.CharField(default=None, max_length=30, null=True)),
                ('city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.cityinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.tguser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('file_id', models.CharField(max_length=250)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.review')),
            ],
            options={
                'verbose_name': 'Файл для Отзыв/Идея',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.tguser'),
        ),
        migrations.CreateModel(
            name='MetalToSalePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('proba', models.CharField(max_length=30)),
                ('cash_price', models.FloatField(null=True)),
                ('card_price', models.FloatField(null=True)),
                ('transfer_price', models.FloatField(null=True)),
                ('metal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.metaltosale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('phone_number', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=80)),
                ('city_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.cityinfo')),
            ],
            options={
                'verbose_name': 'Контакты филиала',
            },
        ),
        migrations.CreateModel(
            name='CityAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('address', models.CharField(max_length=140)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.cityinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('count', models.IntegerField(default=1)),
                ('gem_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.gemtobuy')),
                ('metal_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.metaltobuy')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sales')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('phone_number', models.CharField(max_length=30)),
                ('datetime_call', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.tguser')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
            },
        ),
    ]
