# Generated by Django 4.0.6 on 2022-08-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemtobuy',
            name='size',
            field=models.CharField(max_length=40),
        ),
    ]
